const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const base = process.env.BASE_URL || 'http://127.0.0.1:8765';
const guide = process.env.GUIDE_URL || 'http://127.0.0.1:18766/guia/';
const out = process.env.SCREENSHOT_DIR || '/home/nmaldaner/projetos/output/jev-verificacao';
(async () => {
  fs.mkdirSync(out, {recursive:true});
  const browser = await chromium.launch({headless:true,args:['--no-sandbox']});
  try {
    const page = await browser.newPage({viewport:{width:1440,height:1000}});
    const errors = []; page.on('pageerror', e => errors.push(e.message));
    await page.goto(base); await page.locator('#cases button').last().waitFor();
    const examples = JSON.parse(fs.readFileSync(path.join(__dirname,'../app/cases.json')));
    assert.equal(await page.locator('#cases button').count(),20);
    for (const item of examples) {
      await page.locator(`#cases button[data-id="${item.id}"]`).click();
      await page.locator('#simulate').click();
      await page.locator('#result:not([hidden])').waitFor();
      assert.match(await page.locator('#resultMode').innerText(),/SIMULAÇÃO/);
      assert.equal(await page.locator('#answers .answer').count(),Object.keys(item.request.questions).length);
    }
    await page.locator('#caseFilter').fill('inexistente');
    assert.equal(await page.locator('#cases button').count(),0);
    await page.locator('#caseFilter').fill('');
    await page.locator('#cases button').nth(1).click(); await page.locator('#simulate').click();
    assert.match(await page.locator('#decision').innerText(),/Sugestão/);
    await page.locator('#threshold').fill('0.95'); await page.locator('#threshold').dispatchEvent('input');
    assert.match(await page.locator('#decision').innerText(),/Revisar/);
    await page.locator('#state').fill('Texto novo');
    assert.equal(await page.locator('#simulate').isDisabled(),true);
    assert.equal(await page.locator('#result').isVisible(),false);
    await page.locator('#reset').click();
    await page.locator('#advanced summary').click();
    await page.locator('#addQuestion').click();
    assert.equal(await page.locator('#questionSelect option').count(),2);
    assert.equal(await page.locator('#questionType').inputValue(),'noul');
    await page.locator('#questionType').selectOption('score');
    await page.locator('#criteria').fill(JSON.stringify(Array(11).fill('nível')));
    assert.equal(await page.locator('#download').isDisabled(),true);
    await page.locator('#criteria').fill('["baixo","alto"]');
    await page.locator('#removeQuestion').click();
    assert.equal(await page.locator('#questionSelect option').count(),1);
    await page.locator('#reset').click();
    let download = page.waitForEvent('download'); await page.locator('#download').click();
    assert.match((await download).suggestedFilename(),/request.json/);
    await page.locator('#simulate').click();
    download = page.waitForEvent('download'); await page.locator('#exportResult').click();
    const resultFile = await download;
    const exported = JSON.parse(fs.readFileSync(await resultFile.path()));
    assert.equal(exported.origin,'simulation'); assert.ok(exported.request && exported.response);
    await page.locator('#importRequest').setInputFiles({name:'invalid.json',mimeType:'application/json',buffer:Buffer.from('{}')});
    await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('recusada'));
    await page.locator('#importRequest').setInputFiles(path.join(__dirname,'../exemplos/triagem-composta-request.json'));
    await page.waitForFunction(()=>document.querySelector('#caseTitle').textContent==='Sua requisição');
    assert.equal(await page.locator('#questionSelect option').count(),4);
    assert.equal(await page.locator('#simulate').isDisabled(),true);
    await page.locator('#importReport').setInputFiles(path.join(__dirname,'../reports/experimento-regras/report.json'));
    await page.locator('#reportSummary:not([hidden])').waitFor();
    assert.match(await page.locator('#reportSummary').innerText(),/83,?3|83\.3/);
    await page.locator('#theme').click();
    assert.equal(await page.locator('body').evaluate(el=>el.classList.contains('light')),true);
    await page.reload();
    assert.equal(await page.locator('body').evaluate(el=>el.classList.contains('light')),true);
    await page.locator('#theme').click();
    await page.locator('#calls').fill('1'); await page.locator('#tokens').fill('10000');
    assert.match(await page.locator('#costTotal').innerText(),/0,00042/);
    await page.locator('#calls').fill('10000');
    await page.locator('#cases button').nth(1).click(); await page.locator('#simulate').click();
    await page.screenshot({path:path.join(out,'app-desktop.png'),fullPage:true});
    await page.setViewportSize({width:390,height:844});
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
    await page.screenshot({path:path.join(out,'app-mobile.png'),fullPage:true});
    await page.goto(guide); await page.locator('img').first().waitFor();
    await page.screenshot({path:path.join(out,'guia-mobile.png'),fullPage:true});
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
    await page.setViewportSize({width:1440,height:1000});
    await page.screenshot({path:path.join(out,'guia-desktop.png'),fullPage:true});
    assert.deepEqual(errors,[]);
    console.log('OK: 20 casos, múltiplas respostas, edição, validação, importação/exportação, relatórios, tema, custos e desktop/mobile sem overflow ou erros JS.');
  } finally { await browser.close(); }
})().catch(e=>{console.error(e);process.exit(1)});
