'use strict';
const $=id=>document.getElementById(id);let cases=[],current,last=null,lastSimulation=true;
function storeTheme(value){try{localStorage.setItem('jev-theme',value)}catch{}}
try{document.body.classList.toggle('light',localStorage.getItem('jev-theme')==='light')}catch{}
function themeLabel(){$('theme').textContent=document.body.classList.contains('light')?'Tema escuro':'Tema claro'}themeLabel();
$('theme').onclick=()=>{document.body.classList.toggle('light');storeTheme(document.body.classList.contains('light')?'light':'dark');themeLabel()};
function payload(){const p=structuredClone(current.request);p.state=$('state').value;p.questions.decisao.instructions=$('question').value;return p}
function pristine(){return $('state').value===current.request.state&&$('question').value===current.request.questions.decisao.instructions}
function update(){if(!current)return;$('payload').textContent=JSON.stringify(payload(),null,2);$('simulate').disabled=!pristine();last=null;$('result').hidden=true;$('status').textContent=pristine()?'':'Contexto editado. Baixe a requisição ou consulte pelo servidor local; não há resposta simulada para esse texto.'}
function select(item){current=item;last=null;$('caseTitle').textContent=item.title;$('description').textContent=item.description;$('state').value=item.request.state;$('question').value=item.request.questions.decisao.instructions;$('options').replaceChildren();Object.entries(item.request.questions.decisao.criteria).forEach(([k,v])=>{const dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=k;dd.textContent=v;$('options').append(dt,dd)});document.querySelectorAll('#cases button').forEach(b=>b.setAttribute('aria-current',String(b.dataset.id===item.id)));update()}
function policy(){if(!last)return;const a=last.answers.decisao,t=Number($('threshold').value);$('thresholdValue').textContent=t.toFixed(2).replace('.',',');let reason='Sugestão em observação. Nenhuma ação externa executada.';if(current.sensitive)reason='Revisão humana obrigatória neste domínio, independentemente da confiança.';else if(['insuficiente','revisar','nenhum','ambiguo','conflito'].includes(a.choice))reason='Revisar: a alternativa exige intervenção ou mais informação.';else if(a.confidence<t||a.probabilities[a.choice]<.9)reason='Revisar: confidence ou probabilidade abaixo do limiar didático.';$('decision').textContent=reason}
function render(response,simulation){last=response;lastSimulation=simulation;const a=response.answers.decisao;$('result').hidden=false;$('resultTitle').textContent='Alternativa: '+a.choice;$('resultMode').textContent=simulation?'SIMULAÇÃO AUTORAL — números inventados para estudar a política; não são uma medição Jev.':'Resposta da API · modelo '+response.model;$('distribution').replaceChildren();for(const [label,p] of Object.entries(a.probabilities)){const row=document.createElement('div');row.className='bar-row';const name=document.createElement('span'),track=document.createElement('div'),fill=document.createElement('div'),value=document.createElement('span');name.textContent=label;track.className='bar-track';fill.className='bar-fill';fill.style.width=(p*100)+'%';value.textContent=(p*100).toFixed(1)+'%';track.append(fill);row.append(name,track,value);$('distribution').append(row)}$('confidence').textContent='Confidence: '+a.confidence.toFixed(2)+' · campo distinto da probabilidade da alternativa.';$('explanation').textContent=simulation?current.explanation:'As probabilidades não explicam o raciocínio. Confira o contexto e a política antes de usar a sugestão.';$('next').textContent=current.next;policy();$('status').textContent=simulation?'Exemplo didático carregado.':'Resposta recebida. Nenhuma ação externa executada.'}
$('state').oninput=update;$('question').oninput=update;$('threshold').oninput=policy;$('reset').onclick=()=>select(current);$('simulate').onclick=()=>{if(pristine())render(current.fixture,true)};
$('download').onclick=()=>{if(!$('state').value.trim()||!$('question').value.trim()){$('status').textContent='Preencha contexto e pergunta antes de exportar.';return}const blob=new Blob([JSON.stringify(payload(),null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=current.id+'-request.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);$('status').textContent='Requisição exportada. Ela não contém credenciais.'};
$('live').onclick=async()=>{const button=$('live'),sent=JSON.stringify(payload()),caseId=current.id;button.disabled=true;$('status').textContent='Consultando o provedor…';try{const res=await fetch('/api/evaluate',{method:'POST',headers:{'Content-Type':'application/json','X-Jev-Lab':'1'},body:sent,signal:AbortSignal.timeout(10000)});const data=await res.json();if(!res.ok)throw Error(data.error||'Falha na consulta.');if(current.id===caseId&&JSON.stringify(payload())===sent)render(data,false);else $('status').textContent='Consulta concluída para o contexto anterior. Refaça a consulta para o texto atual.'}catch(e){$('status').textContent=e.name==='TimeoutError'?'Tempo esgotado. Revise a conexão local.':e.message}finally{button.disabled=false}};
function cost(){const n=Number($('calls').value),t=Number($('tokens').value),p=Number($('price').value);$('costTotal').textContent=[n,t,p].every(x=>Number.isFinite(x)&&x>=0)&&Number.isInteger(n)&&Number.isInteger(t)?(n*t*p/1e6).toLocaleString('pt-BR',{style:'currency',currency:'USD',minimumFractionDigits:2,maximumFractionDigits:6}):'Revise os valores'};['calls','tokens','price'].forEach(id=>$(id).oninput=cost);cost();
fetch('cases.json').then(r=>{if(!r.ok)throw Error('Não foi possível carregar os casos.');return r.json()}).then(data=>{cases=data;for(const item of cases){const b=document.createElement('button');b.dataset.id=item.id;b.textContent=String(item.number).padStart(2,'0')+' · '+item.title;b.onclick=()=>select(item);$('cases').append(b)}select(cases.find(c=>c.id===location.hash.slice(1))||cases[1])}).catch(e=>{$('caseTitle').textContent='Exemplos indisponíveis';$('status').textContent=e.message+' Recarregue a página.'});
if(['127.0.0.1','localhost'].includes(location.hostname))fetch('/api/status').then(r=>r.json()).then(s=>{if(s.local){$('mode').textContent=s.configured?'Servidor local conectado · exemplos simulados; o botão de consulta envia o contexto à TypeSafe.':'Servidor local conectado · chave não configurada. Exemplos didáticos disponíveis.';$('live').hidden=!s.configured}}).catch(()=>{});
